- name: Compile Dopamine
      shell: msys2 {0}
      run: |
        echo "当前目录:"
        pwd
        echo "列出文件:"
        ls -al

        echo "查找所有 C 文件..."
        FILES=$(echo *.c)
        if [ "$FILES" = "*.c" ]; then
          echo "错误: 未找到任何 C 文件"
          exit 1
        fi

        echo "编译文件: $FILES"
        gcc -mconsole -o Dopamine.exe $FILES -luser32 -lgdi32 -lkernel32 -lwinmm -Wall

        echo "检查是否生成 Dopamine.exe..."
        if [ -f Dopamine.exe ]; then
          echo "编译成功: Dopamine.exe"
          ls -lh Dopamine.exe
        else
          echo "编译失败，未找到 Dopamine.exe"
          exit 1
        fi
