name: Build Dopamine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config
        update: true

    - name: Compile Dopamine (safe mode)
      shell: msys2 {0}
      run: |
        echo "当前目录:"
        pwd
        echo "列出当前目录文件:"
        ls -al

        echo "查找所有 C 文件..."
        FILES=$(ls *.c 2>/dev/null || true)
        if [ -z "$FILES" ]; then
          echo "错误: 未找到任何 C 文件"
          exit 1
        fi

        echo "即将编译文件: $FILES"
        gcc -mconsole -o Dopamine.exe $FILES -luser32 -lgdi32 -lkernel32 -lwinmm -Wall

        echo "检查 Dopamine.exe 是否存在..."
        if [ -f Dopamine.exe ]; then
          echo "编译成功: Dopamine.exe"
          ls -lh Dopamine.exe
        else
          echo "编译失败，未找到 Dopamine.exe"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dopamine
        path: Dopamine.exe
