name: Build Dopamine with CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MSYS2 and dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config
        update: true

    - name: Install CMake via Chocolatey
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Configure project with CMake
      shell: msys2 {0}
      run: cmake -S . -B build

    - name: Build project with CMake
      shell: msys2 {0}
      run: cmake --build build --config Release

    - name: Check built executable
      run: dir build\Dopamine.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dopamine
        path: build/Dopamine.exe
