name: Build Dopamine (MSVC & MinGW with Header Check)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-msvc:
    name: Build with MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure with CMake (MSVC)
        run: cmake -S . -B build-msvc -G "Visual Studio 17 2022" -A x64

      - name: Build with MSVC
        run: cmake --build build-msvc --config Release

      - name: Upload MSVC build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dopamine-msvc
          path: build-msvc/Release/*.exe

  build-mingw:
    name: Build with MinGW
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MinGW)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake
          update: true

      - name: Configure and build with MinGW + Header Check
        shell: msys2 {0}
        run: |
          cmake -S . -B build-mingw -G "MinGW Makefiles"
          cmake --build build-mingw --config Release

      - name: Upload MinGW build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dopamine-mingw
          path: build-mingw/Dopamine.exe
